; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "NovaWake"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "PuffDesigns"
#define MyAppURL "https://solidbilla.com"
#define MyAppExeName "Novawake.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (Generated a unique GUID for Novawake)
AppId={{5D46B23F-8C16-4B85-A5D8-A8A246B23F32}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; LicenseFile=License.txt (Optional: Add path to MIT License if needed)
; Remove the line below if you want to run in administrative install mode (install for all users, requires admin privileges).
PrivilegesRequired=admin
OutputBaseFilename=NovaWake-v1.1.0-Setup
SetupIconFile=Assets\logo.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
AppMutex=Novawake_Unique_Mutex_Name_2026
CloseApplications=yes
RestartApplications=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "bin\Release\net8.0-windows10.0.19041.0\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pdb"
Source: "Assets\logo.ico"; DestDir: "{app}\Assets"; Flags: ignoreversion

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Comment: "NovaWake - Keep your PC awake"; IconFilename: "{app}\Assets\logo.ico"; AppUserModelID: "PuffDesigns.Novawake"
Name: "{userdesktop}\NovawakeHotkey"; Filename: "{app}\{#MyAppExeName}"; Parameters: "--shortcut-launch"; WorkingDir: "{app}"; HotKey: "ctrl+alt+n"; Comment: "NovaWake keyboard shortcut launcher"; IconFilename: "{app}\Assets\logo.ico"; AppUserModelID: "PuffDesigns.Novawake"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; AppUserModelID: "PuffDesigns.Novawake"

[InstallDelete]
Type: files; Name: "{commonprograms}\Novawake.lnk"
Type: files; Name: "{commonprograms}\Novawake Quick Start.lnk"
Type: files; Name: "{userprograms}\Novawake.lnk"
Type: files; Name: "{userprograms}\NovawakeHotkey.lnk"
Type: files; Name: "{userdesktop}\NovawakeHotkey.lnk"

[Run]
Filename: "{cmd}"; Parameters: "/C attrib +h +s ""{userdesktop}\NovawakeHotkey.lnk"""; Flags: runhidden
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{userdesktop}\Novawake.lnk"
Type: files; Name: "{userdesktop}\NovawakeHotkey.lnk"
Type: files; Name: "{userstartup}\Novawake.lnk"
Type: files; Name: "{userprograms}\NovawakeHotkey.lnk"
Type: filesandordirs; Name: "{localappdata}\Novawake"
